---
- name: Converge
  hosts: all
  gather_facts: false
  tasks:
    - name: Include blueprints.jenkins_integrations.gitlab_oauth with caller-supplied variables
      ansible.builtin.include_role:
        name: blueprints.jenkins_integrations.gitlab_oauth
      vars:
        jenkins_integration_gitlab_endpoint: "https://example.invalid"
